bw2/ConfigArgParse

- configargparse.py
- setup.py
- tests/test_configargparse.py
- tox.ini
> Support for Python2.6 (without argparse tests)

- configargparse.py
- tests/test_configargparse.py
This is a basic refactoring to address #21, I'm working on testing it with custom parser now... All tests are passing, so hopefully I did not mess up anything.
The documentation and examples in the README will be updated based on input from others.
> Refactor config file parsing

- configargparse.py
- setup.py
- tests/test_configargparse.py
From https://docs.python.org/dev/library/argparse.html#dest: Any internal - characters will be converted to _ characters to make sure the string is a valid attribute name
Also bumped the version to `0.10.0` to be more semvar since `0.9.4` was really feature addition.
> Ensure auto_env_var_prefix converts dash to underscore like ArgParse

- .gitignore
- README.rst
- configargparse.py
- setup.py
- tests/test_configargparse.py
Hi @cortesi @lahwaacz @acx2015 @bartekbrak @kuba (and anyone else interested), 
It'd be great to get your feedback on this PR which builds on @lahwaacz 's PR #28. It moves all remaining logic involving config file formats into `ConfigFileParser` subclasses. The format can then be specified by just setting the new `config_file_parser_class` constructor arg (similar to HelpFormatters). Also, there's now a new `YAMLConfigFileParser` as an alternative to the `DefaultConfigFileParser`. 
Depending on feedback (or if there's none during the next week), I'll merge this and create a new release (probably v1.0). 
This should also fix #19 and #30 (and also #26 - the fix for that became clear while working on this).
> Moved all syntax-related decisions to ConfigFileParser subclasses. Added YAMLConfigFileParser

- configargparse.py
yaml.load can call arbitrary functions, which is incredibly dangerous.
Use yaml.safe_load instead.
> YAMLConfigFileParser: use yaml.safe_load

- configargparse.py
When there are no config args, config_arg_string is the empty string.
Run the list through filter to remove the empty string and fix the help
output.
Fixes #40
> Fix config help when there are no config args

- configargparse.py
- tests/test_configargparse.py
Fix the parsing regex to allow whitespace within values when the key and
value are only separated by whitespace.
> Allow whitespace within values in all cases

- configargparse.py
- tests/test_configargparse.py
https://github.com/bw2/ConfigArgParse/issues/60
Unless there's some side effect that I'm missing, the only test that failed here was the:
`        self.assertParseArgsRaises("Unexpected line 0",
config_file_contents="z z#")`
that tests for a comment delimiter in there. 
With this change value for key z becomes z#
> Accept # and ; as values

- configargparse.py
I ran into the following issue:
When I create a configargparser with Parser(default_config_files=(some, tuple, of strs)), parser.print_help() fails, because it tries to append default_config_files to a list object, and directly merging tuples and lists doesn't work.
This is a simple fix to coerce both sequences into a tuple (chosen as the most lightweight and type) within print_help() before trying to merge them.  Seems to fix the issue with minimal invasiveness.
> Small fix for print_help() when default_config_files is a non-list sequence

- configargparse.py
- tests/test_configargparse.py
For action types that don't need a value, specifying "true"/"yes" will
convert the args but specifying "false"/"no" will not.
fixes #87
> Convert boolean arg only when set to "true"/"yes"

- configargparse.py
- tests/test_configargparse.py
When a long version of the args_for_writing_out_config_file was present, the flag
and a value of True would be written to the resultant config file.  This
prevents those arguments from being populated into the config file.
example:
> my_script.py --write-config ~/.my_config --taco=bell
Contents of ~/.my_config
> write-config = True
> taco = bell
I made these changes without discussing if they are correct or not, so please don't hesitate to criticize as needed.
> Prevent writing args_for_writing_out_config_file to file

- configargparse.py
- tests/test_configargparse.py
I modified the relevant unit test and made it pass.  I wasn't able to get the test.test_argparse tests working (drop-in replacement testing), but I don't believe they should be affected.  If you can give me more info on how to get those tests working, I'd be happy to test those as well.
> fix https://github.com/bw2/ConfigArgParse/issues/69

- configargparse.py
- tests/test_configargparse.py
Config file args were being incorrectly passed as strings in one of the
checks and if a character of the string happened to match a single
character of the command line the config arg would be ignored
fixes #76
> Fix config file args incorrectly matching to command line args

- configargparse.py
- tests/test_configargparse.py
Allows for list input from environment-variables if correctly configured.
Previously always detected input as string-type
> Convert env-var string-lists to actual python-lists.

- configargparse.py
- tests/test_configargparse.py
If argument do not support lists (nargs = None, action='store') and environment variable is list like (values in square bracket separated by comma), the value should not be parsed as list.
> Environment list

- configargparse.py
To suppress loading configuration files, passing `config_file_contents=''` seems like the natural solution. However, this does not what is expected. This changes this.
> Handle empty config_file_contents

- .travis.yml
- configargparse.py
- tests/test_configargparse.py
> All kwargs that are irrelevant to ConfigArgParse are blindly pushed to argparse

- tests/test_configargparse.py
Running the unit tests on Mac OSX with Python 3.6.1 gives me two unit test failures:
```
======================================================================
FAIL: testBasicCase2 (__main__.TestBasicUseCases)
----------------------------------------------------------------------
Traceback (most recent call last):
File "test_configargparse.py", line 239, in testBasicCase2
'positional arguments:\n'
AssertionError: Regex didn't match: 'usage: .* \\[-h\\] --genome GENOME \\[-v\\] -g MY_CFG_FILE \\[-d DBSNP\\]\\s+\\[-f FRMT\\]\\s+vcf \\[vcf ...\\]\n\n(.+\\s+)(.+\\s+)(.+\\s+)(.+\\s+)(.+\\s+)(.+\\s+)(.+\\s+)(.+\\s+)(.+\\s+)positional arguments:\n  vcf \\s+ Variant file\\(s\\)\n\noptional arguments:\n  -h, --help \\s+ show this help message and exit\n  --genome GENOME \\s+ Path to genome file\n …
```
> Fix unittests on Python 3.6.

- configargparse.py
Hi,
When I use a a version action like so : 
```python
misc_group = parser.add_argument_group('Miscellaneous commands')
misc_group.add_argument("-h", "--help", action="help", help="show this help message and exit")
misc_group.add_argument('--version', action='version', version='%(prog)s {version}'.format(version=get_version()), env_var=None)
```
It displays the following : 
```
Miscellaneous commands:
-h, --help            show this help message and exit
--version             show program's version number and exit [env var:
PREFIX.VERSION]
```
The env var PREFIX.VERSION for the `--version` action should not be displayed as it is an action with same behavior as `--help`. This PR should fix it.
And by the way, thanks for this awesome piece of work that will save me a lot of time. 
Cheers!
> Fix to remove env variable handler on argparse.VersionAction

- tests/test_configargparse.py
The tests rely on specific wrapping of text, so set COLUMNS to enforce
it reliably.
The alternatively would be to make tests accept any wrapping, i.e. any
amounts of whitespace between words and therefore would be more work
for no apparent benefit.
Fixes #146, #163
> Set COLUMNS=80 in tests to fix failures

- configargparse.py
Fix help output for suppressed args.
Example:
```
parser.add(
"--debug",
env_var="DEBUG",
action='store_true',
help=SUPPRESS
)
```
Help output without fix:
```
--debug                     ==SUPPRESS== [env var: DEBUG]
```
> Fix help output of suppressed args

- README.rst
- configargparse.py
added to the docs per your request in #172 and fixed a minor bug related to parsing multi-line strings.
> add README docs for ConfigparseConfigFileParser class

- configargparse.py
I am stupid and didn't actually fix the behavior for combining append and nargs in #178 
I intended to allow actions of type append to accept lists when used with nargs=+,* or an int > 1 but I forgot to include the check that the action is append. 
I also introduced a bug in #178 by not checking for nargs=None, which I apologize for, and am glad to see it was fixed quickly. This time I handle None correctly.
> Redo fix for nargs and append

- configargparse.py
- tests/test_configargparse.py
I use the [smart-open](https://github.com/RaRe-Technologies/smart_open) as the `config_file_open_func` to open the config from S3, but `os.path.isfile` would block this operation.
As the config file would be opened in `_open_config_files`, we could actually know if there's any error.
Therefore it removes `os.path.isfile` and use try catch to wrap the opener function for this scenario.
> Not to use `os.path.isfile`

- configargparse.py
This fixes #198 where null values in a yaml config file were stored as "None" string instead of None.
> fix null to str(None) with YAMLConfigFileParser (issue#198)

- README.rst
According to the example, I think the name should be `config_test.py`
> change script file name README

- configargparse.py
- tests/test_configargparse.py
For args that are setup as:
add_arg('--m', action="append", nargs=3, metavar=("<a1>", "<a2>", "<a3>"),)
(action append and nargs>1)
... parse the input file as an array of arrays:
m = [[1, 2, 3], [4, 5, 6]]
> Add support for args with action append and nargs>1

- setup.py
Fixes error `AttributeError: 'module' object has no attribute 'test_configargparse'`
Credits to @hlieberman for finding the cause.
Fixes #125.
> Add mock to test requirements.

- configargparse.py
- tests/test_configargparse.py
Fix all warnings and errors in the test suite. All test can now be run as either `python setup.py test` or `pytest`. Even in most verbose `pytest -r A -W d`.
See #213 or individual commits for details.
> Eliminate warnings in tests

- configargparse.py
- tests/test_configargparse.py
E.g. for an `action=count`, called `verbose`/`v`
you already could set `-v -v -v` (or `-vvv`) on the command line.
And you can now also set:
verbose=3
in the configuration file.
Added two tests to verify current behaviour.
Note that it still is not possible to specify `-v=3` on the command line.
Credits to @christensonb for suggesting this fix in #138.
Closes #138
Closes #175
> Allow setting counters in configfile.

- configargparse.py
- tests/test_configargparse.py
This allows for empty values: `key=` or `key=""`. This is different from specifying `key` without a value (with still sets `key` to "true").
Closes #103
Closes #136
This allows for negative values, or values that start with a dash: `key=-10`, `key=-A38E-8`
Closes #137 (though that most likely was already resolved by #160)
This allows to specify special characters, by putting them in quotes (either ' or " quotes): `key=":"`, `key="="`, `key="#"`, `key="'"`, `key='"'`, etc.
Also adds test suites to explicitly test for the different values and syntaxes. Beware that by adding these test suites some explicity choices are made in particular to the allowed syntax of keys. Previously keys may contain more or less any character (at least according to the parser). ~~Now, allowed characters are: …
> Rewrite DefaultConfigFileParser.parse()

- configargparse.py
- setup.py
- tests/test_configargparse.py
Add `ignore_help_args` option to parse_known_args(..) to avoid exiting the first time this method is called when -h is specified. This can allow all arg definitions to be executed before -h is handled, even if these definitions are interleaved with calls to parse_known_args(..)
> add ignore_help_args option to parse_known_args(..) 

- tests/test_configargparse.py
In Python 3.10, `argparse` uses `options:` instead of `optional arguments:`, and this broke some of the tests.
Add a condition to check the Python version and look for `options:` in the `argparse` output if the Python version is 3.10 or higher.
Fixes bw2/ConfigArgParse#225
Signed-off-by: Major Hayden <major@mhtx.net>
> Handle different argparse output in Python 3.10

- .github/workflows/apidocs.yml
- .gitignore
- apidocs.sh
- configargparse.py
- tox.ini
This adds the API docs generation to the github workflow.
As well as the tox command `tox -e apidocs`. 
See #228
> Add API doc generation

- configargparse.py
This adopts a similar fix that was made for loading similar args from config file in #206, just applying the same to environment variables. This comes from the same use case @ianco describes in #200.
> fix: append with nargs > 1 for env vars

- README.rst
Hi,
A nice way of using lists in yaml is 
```
my_variable:
- value1
- value2
- value3
```
Naively following the documentation to initially set up ConfigArgParse it seemed to accept some yaml input
```
name: value    # (yaml style)
```
but not the above mentioned type of list. 
There is a quote about "subset of YAML syntax".
However, it turns out that the yaml style list is supported.   ;-)    Since that's the case, could be a bit clearer to show it in the docs.
> Update yaml doc

- README.rst
- configargparse.py
Hello @bw2, 
This PR adds TOML and INI parsers with support for sections.
This PR solves issues #250, #227 and #20. 
I know you manifested medium interest into this feature, but I'm sending a PR anyway because I think I propose a good way to integrate `configargparse` config parsing with standard project config files likes `setup.cfg` or `pyproject.toml`. 
I've added pretty extensive documentation, so everything should be clear by reading the readme additions. 
Tell me if you are interested into merging this kind of feature, I think it would be very useful (and I'm not the only one). 
I did not migrated the tests yet, I wanted to hear back from you before continuing working on this. 
Tell me what you think :)
Thanks
> Useful config parsers - TOML and INI parsers with support for sections

- .travis.yml
- README.rst
- setup.py
- tox.ini
Now import `configargparse` on Python 2 fail
```
Python 2.7.18 (default, Jul  1 2022, 12:27:04)
[GCC 9.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import configargparse
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "configargparse.py", line 406
raise ValueError(f"Error trying to unquote the quoted string: {text}: {e}") from e
^
SyntaxError: invalid syntax
>>>
```
> Remove Python 2 support

- configargparse.py
Having `Path` objects in the default_config_files make it impossible to display the help (-h) message
```python
from pathlib import Path
import configargparse
p = configargparse.ArgumentParser(default_config_files=[Path("~/.my_settings.ini")])
p.add("geotiff")
p.add("--flag", help="Flag that can be set in the config file")
options = p.parse_args()
```
Running the above snippet with -h will trigger a `TypeError: sequence item 0: expected str instance, PosixPath found`.
This PR just casts the default_config_files to str in the help message.
> Handle pathlib Path used as default_config_files
