README.rst

Add another config/arg module with pros/cons to "Previously existing modules" section

---

configargparse.py

Added code to match `--foo=bar`, delete it from `args` list, and append both `--foo` and `bar`.

Fix issue 36

---

configargparse.py
tests/test_configargparse.py

Implements #82 for both env vars and config files

Boolean args can be 0 or 1 in env vars and in config files.

---

configargparse.py
tests/test_configargparse.py

Positional args are no longer consumed by list args read from env/config

---

configargparse.py
tests/test_configargparse.py

Fix saving config file for options with multiple arguments.

---

configargparse.py
setup.py
tests/test_configargparse.py

Dash supported as first char of argument

---

configargparse.py
tests/test_configargparse.py

Allow an `open_func` parameter in ArgumentParser constructor and default
to open if not passed. This lets us access configuration files that
are stored remotely, e.g. on GCS or S3.

Add Support for Custom File Openers

---

configargparse.py

- subclass name: ConfigparserConfigFileParser
- allows multi-line values in your config file.
- requires config file to conform to INI file syntax.
- INI sections names still read as comments.
This pull request resolves issue #172

Add ConfigFileParser subclass with pure configparser syntax

---

configargparse.py

Allow append and nargs to be used together with a nested list in config

---

configargparse.py
tests/test_configargparse.py

This fixes the issue with unit tests.

Resubmit issue 207

---

.github/workflows/test.yml
setup.py
tests/test_configargparse.py

Setup tests in github actions

---

README.rst
configargparse.py

Add more types and links to the docstrings.
Only thing: GitHub Pages needs to be enabled afterwards in the repository settings, select `gh-pages` branch,

Docs update

---

configargparse.py

add support for argparse.BooleanOptionalAction  (new in python v3.9+)

---

configargparse.py
tests/test_configargparse.py

This fix the reading from config file of argparse.boolean optional action (see #245).

Fix reading from config file of argparse.boolean optional action

---

configargparse.py

If the LibYAML (C-based YAML dumper/loader) are available, prefer these over the Python-based ones for the sake of speed. See https://pyyaml.org/wiki/PyYAMLDocumentation

Use faster LibYAML bindings if available

---

.github/workflows/test.yml
tests/test_configargparse.py

This PR only adds a test. I wasn't sure why some functionalities wasn't working with my TOML config parser, so I decided to write. test with the YAML config parser that mimics my issue. 
It passes as expected :) So there is an issue with my code. 
Anyway, I figured you'd maybe wanted to have this test anyhow.

Add a test and remove windows from the CI for now

---

tox.ini

Finally the `google` docformat is released, and also some enchantements that will make the longer names wrap :)

Update version of pydoctor.

---

.coveragerc
.github/workflows/test.yml
setup.py

Adds CI coverage
See the current run:

Adds coverage

---

.github/workflows/test.yml
setup.py

I know we discussed ruff, but the code is already formatted with black. I figure, add this quick PR to get the linters working at the very least, and then introduce ruff.

Adds black

---

setup.py
tests/test_configargparse.py

* adds subtests to tests to improve readability if there is a failure 
* adds pytest support for subtests

Improve tests with subtests

---

configargparse.py

Sorts out the imports, there were a lot of 1st party imports that don't need to be embedded into the functions.

Fixes imports
